spring.application.name=SlideHub
server.port=8080

# Ruta para el microservicio de IA 
spring.cloud.gateway.routes.id=ai-service-route
spring.cloud.gateway.routes.uri=lb://ai-service
spring.cloud.gateway.routes.predicates=path=/api/ai/**
spring.cloud.gateway.routes.filters=StripPrefix=2

